### ISSUE TITLE
Change Password - Incomplete Implementation

### ISSUE THREAD

**Issue by loganpmahan** [elliotBraem/CupSave#51]
The change password screen requires both old and new password, however does not verify the success or failure of the password change. The change password button, upon successfully entering the “old password” with a “new password”, does not actually change the password.

Suggestions: Simply including feedback upon failure or success would greatly improve the user’s understanding of the mechanics of the page, however implementing the password change in the backend is necessary before considering an indicator for the user.

**Comment by thenerdjake** [comment]
I just double checked the change password implementation and my password was changed. Can you give a description on how you tried to change your password?

**Comment by loganpmahan** [comment]
My bad, a teammate reported this. Just tried it myself and it worked just fine. They probably inputted incorrect information!
